library(sqldf)
datapath <- "household_power_consumption.txt"
hpc <- read.csv.sql(datapath, sql= "select* from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep = ";")
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$DateTime <- strptime(paste(hpc$Date, hpc$Time), format = "%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(x=hpc$DateTime,y=hpc$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(x=hpc$DateTime,y=hpc$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(x=hpc$DateTime,y=hpc$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(x=hpc$DateTime,y=hpc$Sub_metering_2,col="red")
lines(x=hpc$DateTime,y=hpc$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n",col=c("black","red","blue"),lwd=2,cex=0.4, text.width = 35970.63)
plot(hpc$DateTime, hpc$Global_reactive_power, type = "l", main = "", xlab = "datetime", ylab= "Global_reactive_power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()