library(sqldf)
datapath <- "household_power_consumption.txt"
hpc <- read.csv.sql(datapath, sql= "select* from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep = ";")
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$DateTime <- strptime(paste(hpc$Date, hpc$Time), format = "%Y-%m-%d %H:%M:%S")
plot(x=hpc$DateTime, y=hpc$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="",)
lines(x=hpc$DateTime, y=hpc$Sub_metering_2, col="red")
lines(x=hpc$DateTime, y=hpc$Sub_metering_3, col="blue")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1, cex = 0.6, text.width = 35970.63)
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()